name : Next JS Public Repo Deploy To the EC2 Via CI-Cd and Github Actions
on : [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -name: Sample Test runs
      -run : echo "Raam Raam Bhai"